In [92]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine

load_dotenv()

True

In [93]:
engine = create_engine(
    f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

In [94]:
df_cliente = pd.read_sql(
    "SELECT * FROM raw.cliente",
    engine
)

df_cliente.head()

,cliente_id,endereco_id,nome,cpf,telefone,email,status
0,1,1,João Silva,123.456.789-01,(85)99999-1111,JOAO@EMAIL.COM,Ativo
1,2,2,Maria Oliveira,12345678902,85999992222,maria@email.com,ativo
2,3,3,CARLOS SOUZA,123.456.789-03,85 99999-3333,CARLOS@GMAIL.COM,ATIVO
3,4,4,Ana Beatriz,12345678904,(85)98888-4444,ana@email.com,Inativo
4,5,5,Pedro Henrique,123.456.789-05,85988885555,pedro@gmail.com,ATIVO

In [95]:
pd.read_sql("""SELECT DISTINCT nome, cpf, telefone, email, status FROM raw.cliente;""", engine)

,nome,cpf,telefone,email,status
0,Carla Dias,12345678930,85955440000,carla@email.com,ATIVO
1,Camila Rocha,12345678910,85966661010,camila@email.com,Ativo
2,Lucas Ferreira,123.456.789-07,(85)97777-7777,lucas@email,Ativo
3,CARLOS SOUZA,123.456.789-03,85 99999-3333,CARLOS@GMAIL.COM,ATIVO
4,Aline Souza,123.456.789-25,(85)97766-5555,ALINE@EMAIL.COM,ativo
5,Maria Oliveira,12345678902,85999992222,maria@email.com,ativo
6,Patricia Gomes,12345678912,85955552222,PATRICIA@EMAIL.COM,ativo
7,João Silva,123.456.789-01,(85)99999-1111,JOAO@EMAIL.COM,Ativo
8,Pedro Henrique,123.456.789-05,85988885555,pedro@gmail.com,ATIVO
9,Felipe Nunes,123.456.789-15,(85)93333-5555,felipe@email.com,Inativo
10,Vanessa Lopes,12345678918,(85)92222-8888,vanessa@email.com,ATIVO
11,Cláudio Pereira,12345678924,85988774444,claudio@email.com,ATIVO
12,Amanda Ribeiro,12345678914,85944444444,amanda@gmail.com,ATIVO
13,Bianca Fernandes,12345678920,(85)91111-0000,BIANCA@EMAIL.COM,ATIVO
14,Marcos Paulo,12345678922,85900002222,marcos@email.com,ATIVO
15,Joao Silva,123.456.789-21,(85)90000-1111,joao@email.com,ativo
16,Juliana Lima,12345678906,85999996666,JULIANA@HOTMAIL.COM,ativo
17,Thiago Barbosa,123.456.789-17,85922227777,thiago@email.com,ativo
18,Eduardo Santos,123.456.789-13,(85)94444-3333,eduardo@email.com,Ativo
19,Larissa Melo,12345678916,85933336666,LARISSA@EMAIL.COM,ATIVO
20,Fernanda Costa,12345678908,85977778888,fernanda@email.com,ATIVO
21,Renata Moura,123.456.789-23,(85)98877-3333,RENATA@EMAIL.COM,Ativo
22,Jessica Lima,12345678928,85966558888,JESSICA@EMAIL.COM,ATIVO
23,Diego Castro,12345678926,85977665555,diego@email.com,ATIVO
24,Bruno Martins,123.456.789-11,(85)95555-1111,bruno@email.com,ATIVO
25,Ricardo Mendes,123.456.789-29,(85)95544-9999,ricardo@email.com,ativo
26,Gabriel Araújo,123.456.789-19,85911119999,gabriel@email.com,Ativo
27,Paulo César,123.456.789-27,(85)96655-7777,paulo@email,Ativo
28,Ana Beatriz,12345678904,(85)98888-4444,ana@email.com,Inativo
29,Roberto Alves,123.456.789-09,(85)96666-9999,ROBERTO@EMAIL.COM,ativo

In [96]:
pd.read_sql(""" SELECT table_name FROM information_schema.tables WHERE table_schema ='raw';""", engine)

     table_name
0       veiculo
1         venda
2     pagamento
3   funcionario
4    fornecedor
5          loja
6       cliente
7         cargo
8      endereco
9         marca
10       modelo

In [97]:
df_cliente.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cliente_id   30 non-null     int64
 1   endereco_id  30 non-null     int64
 2   nome         30 non-null     str
 3   cpf          30 non-null     str
 4   telefone     30 non-null     str
 5   email        30 non-null     str
 6   status       30 non-null     str
dtypes: int64(2), str(5)
memory usage: 1.8 KB

In [98]:
df_cliente.describe()

       cliente_id  endereco_id
count   30.000000    30.000000
mean    15.500000    15.500000
std      8.803408     8.803408
min      1.000000     1.000000
25%      8.250000     8.250000
50%     15.500000    15.500000
75%     22.750000    22.750000
max     30.000000    30.000000

In [99]:
df_cliente["status"].value_counts()

status
ATIVO      13
ativo       8
Ativo       7
Inativo     2
Name: count, dtype: int64

In [100]:
df_cliente.isnull().sum()

cliente_id     0
endereco_id    0
nome           0
cpf            0
telefone       0
email          0
status         0
dtype: int64

In [101]:
df_cliente["status"].unique()

<StringArray>
['Ativo', 'ativo', 'ATIVO', 'Inativo']
Length: 4, dtype: str

In [102]:
df_cliente.duplicated().sum()

np.int64(0)