In [7]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine

In [8]:
load_dotenv()

True

In [9]:
engine = create_engine(
    f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

In [10]:
df_veiculo = pd.read_sql('SELECT * FROM raw.veiculo', engine)

In [11]:
df_veiculo.head()

,veiculo_id,modelo_id,fornecedor_id,placa,chassi,ano_fabricacao,cor,quilometragem,condicao,status,preco
0,1,1,1,ABC1A11,9BWAA01JX40000001,2024,Branco,15000,Novo,Disponível,115990.0
1,2,2,2,DEF2B22,9BWAA01JX40000002,2024,branco,5000,novo,disponivel,116990.5
2,3,3,3,GHI3C33,9BWAA01JX40000003,2023,Preto,45000,Usado,Disponível,159900.0
3,4,4,4,JKL4D44,9BWAA01JX40000004,2022,preto,68000,USADO,vendido,89990.0
4,5,5,5,MNO5E55,9BWAA01JX40000005,2025,Prata,1000,Novo,Disponível,145000.0

In [12]:
df_veiculo.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   veiculo_id      30 non-null     int64
 1   modelo_id       30 non-null     int64
 2   fornecedor_id   30 non-null     int64
 3   placa           30 non-null     str
 4   chassi          30 non-null     str
 5   ano_fabricacao  30 non-null     int64
 6   cor             30 non-null     str
 7   quilometragem   30 non-null     int64
 8   condicao        30 non-null     str
 9   status          30 non-null     str
 10  preco           30 non-null     float64
dtypes: float64(1), int64(5), str(5)
memory usage: 2.7 KB

In [13]:
pd.read_sql("""
SELECT DISTINCT cor
FROM raw.veiculo
ORDER BY cor;
""", engine)

         cor
0     Branco
1    branco
2     prata
3       azul
4       Azul
5     Branco
6      cinza
7      Cinza
8      Prata
9      preto
10     Preto
11     PRETO
12  vermelho
13  Vermelho

In [14]:
pd.read_sql("""
SELECT DISTINCT condicao
FROM raw.veiculo;
""", engine)

   condicao
0      Novo
1  seminovo
2     Usado
3     USADO
4      novo
5  Seminovo

In [15]:
pd.read_sql("""
SELECT DISTINCT status
FROM raw.veiculo;
""", engine)

       status
0  Disponivel
1     Vendido
2     vendido
3  Disponível
4  disponivel
5  disponível
6  DISPONÍVEL

In [16]:
pd.read_sql("""
SELECT placa, COUNT(*) AS quantidade
FROM raw.veiculo
GROUP BY placa
HAVING COUNT(*) > 1;
""", engine)

Empty DataFrame
Columns: [placa, quantidade]
Index: []

In [17]:
pd.read_sql("""
SELECT chassi, COUNT(*) AS quantidade
FROM raw.veiculo
GROUP BY chassi
HAVING COUNT(*) > 1;
""", engine)

Empty DataFrame
Columns: [chassi, quantidade]
Index: []

In [18]:
pd.read_sql("""
SELECT *
FROM raw.veiculo
WHERE placa IS NULL
   OR chassi IS NULL
   OR preco IS NULL
   OR modelo_id IS NULL
   OR fornecedor_id IS NULL;
""", engine)

Empty DataFrame
Columns: [veiculo_id, modelo_id, fornecedor_id, placa, chassi, ano_fabricacao, cor, quilometragem, condicao, status, preco]
Index: []