In [1]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine

In [2]:
load_dotenv()

True

In [3]:
engine = create_engine(
    f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

In [4]:
df_venda = pd.read_sql("SELECT * FROM raw.venda", engine)

In [11]:
df_venda.head()

,venda_id,cliente_id,funcionario_id,loja_id,veiculo_id,data_venda,valor_total,status
0,1,1,1,1,1,2026-01-10,115990.0,Concluída
1,2,2,2,1,2,2026-01-15,116990.5,concluida
2,3,3,3,2,3,2026-02-01,159900.0,CONCLUIDA
3,4,4,4,2,4,2026-02-05,89990.0,Cancelada
4,5,5,5,3,5,2026-02-18,145000.0,Concluída

In [12]:
pd.read_sql("""
SELECT DISTINCT status
FROM raw.venda;
""", engine)

      status
0  Concluída
1  concluída
2   Pendente
3  CONCLUIDA
4  Cancelada
5  concluida

In [13]:
pd.read_sql("""
SELECT *
FROM raw.venda
WHERE cliente_id IS NULL
   OR funcionario_id IS NULL
   OR loja_id IS NULL
   OR veiculo_id IS NULL
   OR data_venda IS NULL
   OR valor_total IS NULL
   OR status IS NULL;
""", engine)

Empty DataFrame
Columns: [venda_id, cliente_id, funcionario_id, loja_id, veiculo_id, data_venda, valor_total, status]
Index: []

In [14]:
pd.read_sql("""
SELECT venda_id, COUNT(*)
FROM raw.venda
GROUP BY venda_id
HAVING COUNT(*) > 1;
""", engine)

Empty DataFrame
Columns: [venda_id, count]
Index: []

In [15]:
pd.read_sql("""
SELECT DISTINCT data_venda
FROM raw.venda
ORDER BY data_venda;
""", engine)

    data_venda
0   2026-01-10
1   2026-01-15
2   2026-02-01
3   2026-02-05
4   2026-02-18
5   2026-03-02
6   2026-03-10
7   2026-03-15
8   2026-03-20
9   2026-04-01
10  2026-04-05
11  2026-04-10
12  2026-04-18
13  2026-04-22
14  2026-05-01
15  2026-05-05
16  2026-05-10
17  2026-05-15
18  2026-05-20
19  2026-06-01
20  2026-06-05
21  2026-06-10
22  2026-06-15
23  2026-06-20
24  2026-06-25
25  2026-07-01
26  2026-07-05
27  2026-07-10
28  2026-07-12
29  2026-07-15

In [16]:
pd.read_sql("""
SELECT *
FROM raw.venda
WHERE valor_total <= 0;
""", engine)

Empty DataFrame
Columns: [venda_id, cliente_id, funcionario_id, loja_id, veiculo_id, data_venda, valor_total, status]
Index: []

In [17]:
df_venda.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   venda_id        60 non-null     int64
 1   cliente_id      60 non-null     int64
 2   funcionario_id  60 non-null     int64
 3   loja_id         60 non-null     int64
 4   veiculo_id      60 non-null     int64
 5   data_venda      60 non-null     object
 6   valor_total     60 non-null     float64
 7   status          60 non-null     str
dtypes: float64(1), int64(5), object(1), str(1)
memory usage: 3.9+ KB