In [ ]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine

In [ ]:
load_dotenv()

True

In [ ]:
engine = create_engine(
    f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

In [ ]:
df_endereco = pd.read_sql("SELECT * FROM raw.endereco;", engine)

In [ ]:
df_endereco.head()

,endereco_id,rua,numero,bairro,cidade,estado,cep
0,1,Rua das Flores,101,Centro,Fortaleza,CE,60010-000
1,2,RUA DAS FLORES,101,centro,FORTALEZA,ce,60010000
2,3,Av. Beira Mar,2500,Meireles,Fortaleza,Ceará,60165-121
3,4,Av Beira Mar,2500,Meireles,fortaleza,CE,60165121
4,5,Rua A,12,Aldeota,Fortaleza,CE,60150-100

In [ ]:
df_endereco.tail()

,endereco_id,rua,numero,bairro,cidade,estado,cep
55,56,Rua Principal,1,industrial,Horizonte,ce,62880000
56,57,Rua XV de Novembro,750,Centro,Fortaleza,CE,
57,58,Rua XV Novembro,750,Centro,FORTALEZA,CE,NaN
58,59,Rua das Palmeiras,340,Cocó,Fortaleza,CE,60192-150
59,60,Rua das Palmeiras,340,Coco,Fortaleza,ce,60192150

In [ ]:
df_endereco.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   endereco_id  60 non-null     int64
 1   rua          60 non-null     str
 2   numero       56 non-null     str
 3   bairro       60 non-null     str
 4   cidade       60 non-null     str
 5   estado       60 non-null     str
 6   cep          54 non-null     str
dtypes: int64(1), str(6)
memory usage: 3.4 KB

In [ ]:
df_endereco.shape

(60, 7)

In [ ]:
pd.read_sql("SELECT DISTINCT * FROM raw.endereco;", engine)

,endereco_id,rua,numero,bairro,cidade,estado,cep
0,45,Rua sem nome,,Centro,Maracanaú,CE,61900-000
1,48,Trav. das Acacias,45,Jardim America,FORTALEZA,ce,60410300
2,42,Av Santos Dumont,3500,aldeota,FORTALEZA,CE,60150161
3,40,Rua D,15,Centro,Caucaia,ce,61600000
4,4,Av Beira Mar,2500,Meireles,fortaleza,CE,60165121
5,26,Rua Principal,1,industrial,Horizonte,ce,62880000
6,32,RUA DAS FLORES,101,centro,FORTALEZA,ce,60010000
7,37,Rua B,34A,Papicu,Fortaleza,CE,NaN
8,59,Rua das Palmeiras,340,Cocó,Fortaleza,CE,60192-150
9,43,Rua José de Alencar,88,Benfica,Fortaleza,CE,60020-120
10,55,Rua Principal,01,Industrial,Horizonte,CE,62880-000
11,41,Av. Santos Dumont,3500,Aldeota,Fortaleza,CE,60150-161
12,14,Rua Jose de Alencar,88,BENFICA,Fortaleza,ce,60020120
13,28,Rua XV Novembro,750,Centro,FORTALEZA,CE,NaN
14,25,Rua Principal,01,Industrial,Horizonte,CE,62880-000
15,23,Av. Brasil,900,Centro,Quixadá,CE,63900-000
16,57,Rua XV de Novembro,750,Centro,Fortaleza,CE,
17,24,Av Brasil,900,Centro,Quixada,CE,63900000
18,17,Travessa das Acácias,45,Jardim América,Fortaleza,CE,60410-300
19,50,Rua Padre Cicero,150,centro,Juazeiro do Norte,ce,63010020
20,27,Rua XV de Novembro,750,Centro,Fortaleza,CE,
21,11,Av. Santos Dumont,3500,Aldeota,Fortaleza,CE,60150-161
22,58,Rua XV Novembro,750,Centro,FORTALEZA,CE,NaN
23,49,Rua Padre Cícero,150,Centro,Juazeiro do Norte,CE,63010-020
24,30,Rua das Palmeiras,340,Coco,Fortaleza,ce,60192150
25,12,Av Santos Dumont,3500,aldeota,FORTALEZA,CE,60150161
26,2,RUA DAS FLORES,101,centro,FORTALEZA,ce,60010000
27,20,Rua Padre Cicero,150,centro,Juazeiro do Norte,ce,63010020
28,6,Rua A,NaN,Aldeota,Fortaleza,CE,60150-100
29,1,Rua das Flores,101,Centro,Fortaleza,CE,60010-000
30,15,Rua sem nome,,Centro,Maracanaú,CE,61900-000
31,22,Rua Sao Paulo,500,CENTRO,Sobral,ce,62010001
32,3,Av. Beira Mar,2500,Meireles,Fortaleza,Ceará,60165-121
33,21,Rua São Paulo,500,Centro,Sobral,CE,62010-001
34,18,Trav. das Acacias,45,Jardim America,FORTALEZA,ce,60410300
35,39,Rua D,15,Centro,Caucaia,CE,61600-000
36,38,Rua C,200,papicu,FORTALEZA,ce,60190-200
37,56,Rua Principal,1,industrial,Horizonte,ce,62880000
38,51,Rua São Paulo,500,Centro,Sobral,CE,62010-001
39,36,Rua A,NaN,Aldeota,Fortaleza,CE,60150-100
40,44,Rua Jose de Alencar,88,BENFICA,Fortaleza,ce,60020120
41,46,Rua sem nome,NaN,Centro,Maracanau,CE,NaN
42,34,Av Beira Mar,2500,Meireles,fortaleza,CE,60165121
43,33,Av. Beira Mar,2500,Meireles,Fortaleza,Ceará,60165-121
44,54,Av Brasil,900,Centro,Quixada,CE,63900000
45,53,Av. Brasil,900,Centro,Quixadá,CE,63900-000
46,29,Rua das Palmeiras,340,Cocó,Fortaleza,CE,60192-150
47,47,Travessa das Acácias,45,Jardim América,Fortaleza,CE,60410-300
48,35,Rua A,12,Aldeota,Fortaleza,CE,60150-100
49,9,Rua D,15,Centro,Caucaia,CE,61600-000
50,8,Rua C,200,papicu,FORTALEZA,ce,60190-200
51,19,Rua Padre Cícero,150,Centro,Juazeiro do Norte,CE,63010-020
52,5,Rua A,12,Aldeota,Fortaleza,CE,60150-100
53,13,Rua José de Alencar,88,Benfica,Fortaleza,CE,60020-120
54,7,Rua B,34A,Papicu,Fortaleza,CE,NaN
55,10,Rua D,15,Centro,Caucaia,ce,61600000
56,60,Rua das Palmeiras,340,Coco,Fortaleza,ce,60192150
57,31,Rua das Flores,101,Centro,Fortaleza,CE,60010-000
58,16,Rua sem nome,NaN,Centro,Maracanau,CE,NaN
59,52,Rua Sao Paulo,500,CENTRO,Sobral,ce,62010001