In [35]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine

In [36]:
load_dotenv()

True

In [37]:
engine = create_engine(
    f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

In [38]:
df_cargo = pd.read_sql('SELECT * FROM raw.cargo', engine)

In [39]:
df_cargo.head()

   cargo_id       nome
0         1   Vendedor
1         2   vendedor
2         3   VENDEDOR
3         4  Vendedora
4         5    Gerente

In [40]:
pd.read_sql("SELECT DISTINCT nome FROM raw.cargo", engine)

                       nome
0                ESTOQUISTA
1       CONSULTOR DE VENDAS
2                 Vendedora
3                  Vendedor
4                supervisor
5                  VENDEDOR
6                 consultor
7                Estoquista
8   Auxiliar Administrativo
9                  Mecânico
10               Supervisor
11            Gerente Geral
12                CONSULTOR
13  AUXILIAR ADMINISTRATIVO
14            RECEPCIONISTA
15                analista
16            GERENTE GERAL
17
18                 Consltor
19                  Vendedr
20                 vendedor
21                 Analista
22                 gerente
23               assistente
24               Assistente
25               SUPERVISOR
26            Recepcionista
27      Consultor de Vendas
28                Vendedor
29               ASSISTENTE
30            gerente geral
31      consultor de vendas
32            recepcionista
33
34                Analistaa
35  auxiliar administrativo
36                Consultor
37               FINANCEIRO
38                 ANALISTA
39               estoquista
40                  GERENTE
41              financeiro
42                 Gerentee
43               Financeiro
44                MECÂNICO
45                 Mecanico
46                  Gerente

In [41]:
df_cargo.isnull().sum()

cargo_id    0
nome        0
dtype: int64