In [1]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine

In [2]:
load_dotenv()

True

In [3]:
engine = create_engine(
    f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

In [4]:
df_pagamento = pd.read_sql('SELECT * FROM raw.pagamento', engine)

In [10]:
df_pagamento.head()

,pagamento_id,venda_id,forma_pagamento,quantidade_parcelas,desconto,status_pagamento,data_pagamento
0,1,1,Pix,1,0.0,Pago,2026-01-10
1,2,2,pix,1,500.0,pago,2026-01-15
2,3,3,PIX,1,NaN,PAGO,2026-02-01
3,4,4,Cartão de Crédito,12,1000.0,Cancelado,2026-02-05
4,5,5,cartao de credito,24,2500.0,Pago,2026-02-18

In [11]:
pd.read_sql("""
SELECT DISTINCT forma_pagamento
FROM raw.pagamento;
""", engine)

      forma_pagamento
0                pix
1                 pix
2      financiamento
3              Boleto
4       Transferência
5                 Pix
6              BOLETO
7   Cartão de Crédito
8       Financiamento
9            DINHEIRO
10                PIX
11          dinheiro
12      FINANCIAMENTO
13      TRANSFERENCIA
14  Cartao de Credito
15  CARTÃO DE CRÉDITO
16      Transferencia
17           Dinheiro
18             boleto
19  cartao de credito
20     transferencia
21  cartão de crédito

In [12]:
pd.read_sql("""
SELECT DISTINCT status_pagamento
FROM raw.pagamento;
""", engine)

  status_pagamento
0             pago
1             PAGO
2             Pago
3        cancelado
4         Pendente
5        Cancelado

In [13]:
pd.read_sql("""
SELECT *
FROM raw.pagamento
WHERE desconto IS NULL
OR data_pagamento IS NULL;
""", engine)

,pagamento_id,venda_id,forma_pagamento,quantidade_parcelas,desconto,status_pagamento,data_pagamento
0,3,3,PIX,1,NaN,PAGO,2026-02-01
1,6,6,CARTÃO DE CRÉDITO,36,NaN,Pendente,None
2,9,9,FINANCIAMENTO,48,NaN,cancelado,2026-03-20
3,11,11,boleto,1,NaN,PAGO,2026-04-05
4,12,12,BOLETO,1,500.0,Pendente,None
5,14,14,transferencia,1,NaN,PAGO,2026-04-22
6,17,17,dinheiro,1,NaN,Pago,2026-05-10
7,18,18,DINHEIRO,1,500.0,Pendente,None
8,20,20,Cartão de Crédito,18,NaN,PAGO,2026-06-01
9,22,22,PIX,1,NaN,Cancelado,2026-06-10
10,24,24,Cartao de Credito,12,750.0,Pendente,None
11,25,25,cartão de crédito,24,NaN,Pago,2026-06-25
12,28,28,Transferencia,1,NaN,cancelado,2026-07-10
13,30,30,pix,1,0.0,Pendente,None

In [14]:
pd.read_sql("""
SELECT *
FROM raw.pagamento p
LEFT JOIN raw.venda v
ON p.venda_id = v.venda_id
WHERE v.venda_id IS NULL;
""", engine)

Empty DataFrame
Columns: [pagamento_id, venda_id, forma_pagamento, quantidade_parcelas, desconto, status_pagamento, data_pagamento, venda_id, cliente_id, funcionario_id, loja_id, veiculo_id, data_venda, valor_total, status]
Index: []

In [15]:
df_pagamento.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   pagamento_id         30 non-null     int64
 1   venda_id             30 non-null     int64
 2   forma_pagamento      30 non-null     str
 3   quantidade_parcelas  30 non-null     int64
 4   desconto             20 non-null     float64
 5   status_pagamento     30 non-null     str
 6   data_pagamento       25 non-null     object
dtypes: float64(1), int64(3), object(1), str(2)
memory usage: 1.8+ KB