In [2]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine

In [3]:
load_dotenv()

True

In [4]:
engine = create_engine(
    f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

In [5]:
df_modelo = pd.read_sql("SELECT * FROM raw.modelo", engine)

In [13]:
df_modelo.head()

   modelo_id  marca_id       nome  ano_modelo      cambio combustivel
0          1         1    Corolla        2024  Automático        Flex
1          2         1   corolla         2024  automatico        FLEX
2          3         1      Hilux        2023      Manual      Diesel
3          4         1      Yaris        2022         CVT        flex
4          5         2      Civic        2023  Automático        Flex

In [14]:
pd.read_sql("""
SELECT
    lower(trim(nome)) AS nome,
    marca_id,
    COUNT(*) AS quantidade
FROM raw.modelo
GROUP BY lower(trim(nome)), marca_id
HAVING COUNT(*) > 1;
""", engine)

       nome  marca_id  quantidade
0     creta         3           2
1   corolla         1           2
2     civic         2           2
3  sportage        15           2

In [15]:
pd.read_sql("""
SELECT DISTINCT cambio
FROM raw.modelo;
""", engine)

       cambio
0      Manual
1         CVT
2    S-Tronic
3  AUTOMATICO
4  automatico
5  Automático
6  Automatico

In [16]:
pd.read_sql("""
SELECT DISTINCT combustivel
FROM raw.modelo;
""", engine)

  combustivel
0     Híbrido
1        flex
2        FLEX
3      Diesel
4    Gasolina
5        Flex

In [18]:
pd.read_sql("""
SELECT DISTINCT cambio
FROM public.stg_modelo;
""", engine)

       cambio
0      Manual
1         Cvt
2    S-Tronic
3  Automático

In [19]:
pd.read_sql("""SELECT *
FROM raw.modelo
WHERE nome IS NULL
   OR trim(nome) = '';""", engine)

Empty DataFrame
Columns: [modelo_id, marca_id, nome, ano_modelo, cambio, combustivel]
Index: []